[build]
   command = "yarn run build"
   functions = "lambda"
   publish = "build"

[dev]
  command = "yarn start" # Command to start your dev server
  port = 3000 # Port that the dev server will be listening on
  functionsPort = 34567 # port for functions server